import RNHTMLtoPDF from 'react-native-html-to-pdf';
import Share from 'react-native-share';
import { Platform, Alert } from 'react-native';
import type { PredictionResult } from '../components/PredictionResults';

export const generateProfessionalReport = async (
  result: PredictionResult,
  originalImageBase64: string
) => {
  try {
    const timestamp = new Date().toLocaleString();
    const modelName = result.model_type.toUpperCase();
    
    // Construct HTML for the PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Helvetica', sans-serif; padding: 20px; color: #333; }
          .header { border-bottom: 2px solid #4f46e5; padding-bottom: 10px; margin-bottom: 20px; }
          .header h1 { color: #4f46e5; margin: 0; font-size: 24px; }
          .header p { margin: 5px 0 0; color: #64748b; font-size: 12px; }
          
          .section { margin-bottom: 25px; }
          .section-title { font-size: 14px; font-weight: bold; color: #1e293b; border-left: 4px solid #4f46e5; padding-left: 10px; margin-bottom: 15px; text-transform: uppercase; }
          
          .grid { display: flex; flex-wrap: wrap; gap: 20px; }
          .col { flex: 1; min-width: 250px; }
          
          .result-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; }
          .predicted-class { font-size: 20px; font-weight: 800; color: #1e293b; margin: 0; }
          .confidence { font-size: 14px; color: #4f46e5; font-weight: 600; }
          
          .image-container { text-align: center; background: #000; border-radius: 8px; overflow: hidden; margin-top: 10px; }
          .main-img { width: 100%; max-width: 400px; height: auto; }
          
          .xai-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
          .xai-card { background: #f1f5f9; border-radius: 6px; padding: 8px; text-align: center; }
          .xai-card img { width: 100%; border-radius: 4px; background: #000; }
          .xai-card p { font-size: 10px; font-weight: bold; margin-top: 5px; text-transform: uppercase; }
          
          .table { width: 100%; border-collapse: collapse; font-size: 11px; }
          .table th { text-align: left; background: #f1f5f9; padding: 8px; border-bottom: 1px solid #e2e8f0; }
          .table td { padding: 8px; border-bottom: 1px solid #f1f5f9; }
          .top-row { font-weight: bold; color: #4f46e5; }
          
          .footer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 15px; font-size: 10px; color: #94a3b8; text-align: center; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>LULC Classification Report</h1>
          <p>Generated by Deep Learning Recognition System • ${timestamp}</p>
        </div>

        <div class="section">
          <div class="grid">
            <div class="col">
              <div class="section-title">Primary Classification</div>
              <div class="result-box">
                <p class="predicted-class">${result.predicted_class}</p>
                <p class="confidence">Confidence: ${(result.confidence * 100).toFixed(2)}%</p>
              </div>
              
              <div class="section-title" style="margin-top: 20px;">Input Image</div>
              <div class="image-container">
                <img src="${originalImageBase64}" class="main-img" />
              </div>
            </div>
            
            <div class="col">
              <div class="section-title">Detailed Probabilities</div>
              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Class Label</th>
                    <th>Confidence</th>
                  </tr>
                </thead>
                <tbody>
                  ${result.all_predictions.map((pred, i) => `
                    <tr class="${i === 0 ? 'top-row' : ''}">
                      <td>${i + 1}</td>
                      <td>${pred.class_label}</td>
                      <td>${(pred.confidence * 100).toFixed(2)}%</td>
                    </tr>
                  `).join('')}
                </tbody>
              </table>
              
              <div class="section-title" style="margin-top: 20px;">Technical Specs</div>
              <table class="table">
                <tr><td>Model Architecture</td><td>${modelName} Classifier</td></tr>
                <tr><td>Inference Latency</td><td>${result.inference_time_ms.toFixed(2)} ms</td></tr>
                <tr><td>Source Dimensions</td><td>${result.image_info.width} x ${result.image_info.height}</td></tr>
                <tr><td>Source Format</td><td>${result.image_info.format}</td></tr>
              </table>
            </div>
          </div>
        </div>

        ${result.explainability_maps && Object.keys(result.explainability_maps).length > 0 ? `
          <div class="section">
            <div class="section-title">AI Interpretability (XAI Maps)</div>
            <div class="xai-grid">
              ${Object.entries(result.explainability_maps).map(([name, uri]) => `
                <div class="xai-card">
                  <img src="${uri}" />
                  <p>${name.toUpperCase()}</p>
                </div>
              `).join('')}
            </div>
            <p style="font-size: 9px; color: #64748b; margin-top: 10px;">
              * Heatmaps highlight which areas of the satellite image most influenced the AI's decision.
            </p>
          </div>
        ` : ''}

        <div class="footer">
          <p>Confidence: ${result.confidence.toFixed(6)} | Source Hash Verification: OK</p>
          <p>This report is computer-generated for environmental research and monitoring purposes.</p>
        </div>
      </body>
      </html>
    `;

    const options = {
      html: htmlContent,
      fileName: `LULC_Report_${Date.now()}`,
      directory: 'Documents',
    };

    const file = await RNHTMLtoPDF.convert(options);
    
    if (file.filePath) {
      await Share.open({
        url: `file://${file.filePath}`,
        type: 'application/pdf',
        title: 'Share LULC Recognition Report',
      });
    }
  } catch (error) {
    console.error('Report Generation Error:', error);
    Alert.alert('Report Error', 'Failed to generate PDF. Please try again.');
  }
};
